import { createFileRoute } from '@tanstack/react-router'
// Note: styled-system is generated by running `npx panda codegen`
// We assume it exists for the build.
import { css } from '../../styled-system/css'
import { center, vstack } from '../../styled-system/patterns'

export const Route = createFileRoute('/')({
  component: Index,
})

function Index() {
  return (
    <div className={center({ h: '100vh', w: '100vw', bg: 'primary' })}>
      <div className={vstack({ 
          gap: '6', 
          p: '12', 
          bg: 'rgba(51, 65, 85, 0.5)', // Glassmorphism base
          backdropFilter: 'blur(10px)',
          borderRadius: '2xl', 
          border: '1px solid token(colors.accent)',
          boxShadow: '0 0 40px rgba(56, 189, 248, 0.1)',
          maxWidth: 'md',
          w: 'full'
      })}>
        <div className={css({ 
            w: '16', h: '16', 
            bg: 'accent', 
            borderRadius: 'full', 
            display: 'flex', 
            alignItems: 'center', 
            justifyContent: 'center',
            fontSize: '3xl'
        })}>
          ⚡
        </div>
        
        <h1 className={css({ 
            fontSize: '4xl', 
            fontWeight: 'bold', 
            color: 'white',
            letterSpacing: 'tight',
            textAlign: 'center'
        })}>
          CryptoOrchestrator
          <span className={css({ color: 'accent' })}>.2026</span>
        </h1>
        
        <p className={css({ 
            color: 'gray.300', 
            fontSize: 'lg', 
            textAlign: 'center',
            lineHeight: 'relaxed' 
        })}>
          Institutional-grade local trading engine.
          <br />
          Powered by <span className={css({ color: 'white', fontWeight: 'bold' })}>Rust</span> & <span className={css({ color: 'white', fontWeight: 'bold' })}>Polars</span>.
        </p>
        
        <div className={css({ h: '4' })} />
        
        <button className={css({ 
            bg: 'accent', 
            color: 'primary', 
            px: '8', 
            py: '4', 
            rounded: 'lg', 
            fontWeight: 'bold',
            fontSize: 'lg',
            cursor: 'pointer',
            transition: 'all 0.2s',
            _hover: { 
                transform: 'translateY(-2px)',
                boxShadow: '0 10px 20px rgba(56, 189, 248, 0.2)' 
            },
            _active: { transform: 'translateY(0)' }
        })}>
          Launch Terminal
        </button>
        
        <div className={css({ 
            mt: '8', 
            display: 'flex', 
            gap: '4', 
            fontSize: 'sm', 
            color: 'gray.500' 
        })}>
          <span>SLSA Level 3</span>
          <span>•</span>
          <span>MiCA Compliant</span>
          <span>•</span>
          <span>End-to-End Encrypted</span>
        </div>
      </div>
    </div>
  )
}
