"""add_competitive_trading_bots

Revision ID: 7db86ff346ef
Revises: d46b47a2f854
Create Date: 2025-11-30 16:22:26.966100

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7db86ff346ef'
down_revision = 'd46b47a2f854'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dca_bots',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('exchange', sa.String(length=50), nullable=False),
    sa.Column('trading_mode', sa.String(length=10), nullable=False),
    sa.Column('total_investment', sa.Float(), nullable=False),
    sa.Column('order_amount', sa.Float(), nullable=False),
    sa.Column('interval_minutes', sa.Integer(), nullable=False),
    sa.Column('max_orders', sa.Integer(), nullable=True),
    sa.Column('use_martingale', sa.Boolean(), nullable=False),
    sa.Column('martingale_multiplier', sa.Float(), nullable=False),
    sa.Column('martingale_max_multiplier', sa.Float(), nullable=False),
    sa.Column('take_profit_percent', sa.Float(), nullable=True),
    sa.Column('stop_loss_percent', sa.Float(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('orders_executed', sa.Integer(), nullable=False),
    sa.Column('total_invested', sa.Float(), nullable=False),
    sa.Column('average_price', sa.Float(), nullable=False),
    sa.Column('current_value', sa.Float(), nullable=False),
    sa.Column('total_profit', sa.Float(), nullable=False),
    sa.Column('profit_percent', sa.Float(), nullable=False),
    sa.Column('next_order_at', sa.DateTime(), nullable=True),
    sa.Column('last_order_at', sa.DateTime(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('stopped_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('config', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dca_bots_id'), 'dca_bots', ['id'], unique=False)
    op.create_index(op.f('ix_dca_bots_symbol'), 'dca_bots', ['symbol'], unique=False)
    op.create_index(op.f('ix_dca_bots_user_id'), 'dca_bots', ['user_id'], unique=False)
    op.create_table('follows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('follower_id', sa.Integer(), nullable=False),
    sa.Column('trader_id', sa.Integer(), nullable=False),
    sa.Column('allocation_percentage', sa.Float(), nullable=False),
    sa.Column('max_position_size', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('auto_copy_enabled', sa.Boolean(), nullable=False),
    sa.Column('copy_buy_orders', sa.Boolean(), nullable=False),
    sa.Column('copy_sell_orders', sa.Boolean(), nullable=False),
    sa.Column('min_trade_size', sa.Float(), nullable=True),
    sa.Column('max_trade_size', sa.Float(), nullable=True),
    sa.Column('total_copied_trades', sa.Integer(), nullable=False),
    sa.Column('total_profit', sa.Float(), nullable=False),
    sa.Column('last_copied_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['follower_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['trader_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('follower_id', 'trader_id', name='unique_follow')
    )
    op.create_index(op.f('ix_follows_follower_id'), 'follows', ['follower_id'], unique=False)
    op.create_index(op.f('ix_follows_id'), 'follows', ['id'], unique=False)
    op.create_index(op.f('ix_follows_trader_id'), 'follows', ['trader_id'], unique=False)
    op.create_table('futures_positions',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('exchange', sa.String(length=50), nullable=False),
    sa.Column('trading_mode', sa.String(length=10), nullable=False),
    sa.Column('side', sa.String(length=10), nullable=False),
    sa.Column('leverage', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('entry_price', sa.Float(), nullable=False),
    sa.Column('current_price', sa.Float(), nullable=False),
    sa.Column('margin_used', sa.Float(), nullable=False),
    sa.Column('margin_available', sa.Float(), nullable=False),
    sa.Column('liquidation_price', sa.Float(), nullable=False),
    sa.Column('maintenance_margin', sa.Float(), nullable=False),
    sa.Column('stop_loss_price', sa.Float(), nullable=True),
    sa.Column('take_profit_price', sa.Float(), nullable=True),
    sa.Column('trailing_stop_percent', sa.Float(), nullable=True),
    sa.Column('is_open', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('unrealized_pnl', sa.Float(), nullable=False),
    sa.Column('realized_pnl', sa.Float(), nullable=False),
    sa.Column('total_pnl', sa.Float(), nullable=False),
    sa.Column('pnl_percent', sa.Float(), nullable=False),
    sa.Column('liquidation_risk', sa.Float(), nullable=False),
    sa.Column('margin_ratio', sa.Float(), nullable=False),
    sa.Column('opened_at', sa.DateTime(), nullable=False),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('last_updated_at', sa.DateTime(), nullable=False),
    sa.Column('config', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_futures_positions_id'), 'futures_positions', ['id'], unique=False)
    op.create_index(op.f('ix_futures_positions_symbol'), 'futures_positions', ['symbol'], unique=False)
    op.create_index(op.f('ix_futures_positions_user_id'), 'futures_positions', ['user_id'], unique=False)
    op.create_table('grid_bots',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('exchange', sa.String(length=50), nullable=False),
    sa.Column('trading_mode', sa.String(length=10), nullable=False),
    sa.Column('upper_price', sa.Float(), nullable=False),
    sa.Column('lower_price', sa.Float(), nullable=False),
    sa.Column('grid_count', sa.Integer(), nullable=False),
    sa.Column('grid_spacing_type', sa.String(length=20), nullable=False),
    sa.Column('order_amount', sa.Float(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('total_profit', sa.Float(), nullable=False),
    sa.Column('total_trades', sa.Integer(), nullable=False),
    sa.Column('win_rate', sa.Float(), nullable=False),
    sa.Column('grid_state', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('stopped_at', sa.DateTime(), nullable=True),
    sa.Column('last_trade_at', sa.DateTime(), nullable=True),
    sa.Column('config', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_grid_bots_id'), 'grid_bots', ['id'], unique=False)
    op.create_index(op.f('ix_grid_bots_symbol'), 'grid_bots', ['symbol'], unique=False)
    op.create_index(op.f('ix_grid_bots_user_id'), 'grid_bots', ['user_id'], unique=False)
    op.create_table('idempotency_keys',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('result', sa.JSON(), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_idempotency_keys_expires_at'), 'idempotency_keys', ['expires_at'], unique=False)
    op.create_index(op.f('ix_idempotency_keys_key'), 'idempotency_keys', ['key'], unique=True)
    op.create_index(op.f('ix_idempotency_keys_user_id'), 'idempotency_keys', ['user_id'], unique=False)
    op.create_table('infinity_grids',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('exchange', sa.String(length=50), nullable=False),
    sa.Column('trading_mode', sa.String(length=10), nullable=False),
    sa.Column('grid_count', sa.Integer(), nullable=False),
    sa.Column('grid_spacing_percent', sa.Float(), nullable=False),
    sa.Column('order_amount', sa.Float(), nullable=False),
    sa.Column('current_upper_price', sa.Float(), nullable=False),
    sa.Column('current_lower_price', sa.Float(), nullable=False),
    sa.Column('initial_price', sa.Float(), nullable=False),
    sa.Column('upper_adjustment_percent', sa.Float(), nullable=False),
    sa.Column('lower_adjustment_percent', sa.Float(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('total_profit', sa.Float(), nullable=False),
    sa.Column('total_trades', sa.Integer(), nullable=False),
    sa.Column('grid_adjustments', sa.Integer(), nullable=False),
    sa.Column('grid_state', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('stopped_at', sa.DateTime(), nullable=True),
    sa.Column('last_adjustment_at', sa.DateTime(), nullable=True),
    sa.Column('last_trade_at', sa.DateTime(), nullable=True),
    sa.Column('config', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_infinity_grids_id'), 'infinity_grids', ['id'], unique=False)
    op.create_index(op.f('ix_infinity_grids_symbol'), 'infinity_grids', ['symbol'], unique=False)
    op.create_index(op.f('ix_infinity_grids_user_id'), 'infinity_grids', ['user_id'], unique=False)
    op.create_table('strategies',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('strategy_type', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('version', sa.String(), nullable=True),
    sa.Column('parent_strategy_id', sa.String(), nullable=True),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('logic', sa.JSON(), nullable=True),
    sa.Column('is_template', sa.Boolean(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=True),
    sa.Column('backtest_sharpe_ratio', sa.Float(), nullable=True),
    sa.Column('backtest_win_rate', sa.Float(), nullable=True),
    sa.Column('backtest_total_return', sa.Float(), nullable=True),
    sa.Column('backtest_max_drawdown', sa.Float(), nullable=True),
    sa.Column('usage_count', sa.Integer(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('rating_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['parent_strategy_id'], ['strategies.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_strategies_id'), 'strategies', ['id'], unique=False)
    op.create_index(op.f('ix_strategies_user_id'), 'strategies', ['user_id'], unique=False)
    op.create_table('trailing_bots',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('exchange', sa.String(length=50), nullable=False),
    sa.Column('trading_mode', sa.String(length=10), nullable=False),
    sa.Column('bot_type', sa.String(length=20), nullable=False),
    sa.Column('initial_price', sa.Float(), nullable=False),
    sa.Column('current_price', sa.Float(), nullable=False),
    sa.Column('trailing_percent', sa.Float(), nullable=False),
    sa.Column('order_amount', sa.Float(), nullable=False),
    sa.Column('max_price', sa.Float(), nullable=True),
    sa.Column('min_price', sa.Float(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('orders_executed', sa.Integer(), nullable=False),
    sa.Column('total_profit', sa.Float(), nullable=False),
    sa.Column('highest_price', sa.Float(), nullable=False),
    sa.Column('lowest_price', sa.Float(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('stopped_at', sa.DateTime(), nullable=True),
    sa.Column('last_price_update_at', sa.DateTime(), nullable=True),
    sa.Column('last_order_at', sa.DateTime(), nullable=True),
    sa.Column('config', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trailing_bots_id'), 'trailing_bots', ['id'], unique=False)
    op.create_index(op.f('ix_trailing_bots_symbol'), 'trailing_bots', ['symbol'], unique=False)
    op.create_index(op.f('ix_trailing_bots_user_id'), 'trailing_bots', ['user_id'], unique=False)
    op.create_table('wallets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('wallet_type', sa.String(length=20), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('balance', sa.Float(), nullable=False),
    sa.Column('available_balance', sa.Float(), nullable=False),
    sa.Column('locked_balance', sa.Float(), nullable=False),
    sa.Column('total_deposited', sa.Float(), nullable=False),
    sa.Column('total_withdrawn', sa.Float(), nullable=False),
    sa.Column('total_traded', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wallets_currency'), 'wallets', ['currency'], unique=False)
    op.create_index(op.f('ix_wallets_id'), 'wallets', ['id'], unique=False)
    op.create_index(op.f('ix_wallets_user_id'), 'wallets', ['user_id'], unique=False)
    op.create_index(op.f('ix_wallets_wallet_type'), 'wallets', ['wallet_type'], unique=False)
    op.create_table('strategy_versions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('strategy_id', sa.String(), nullable=False),
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('logic', sa.JSON(), nullable=True),
    sa.Column('change_description', sa.Text(), nullable=True),
    sa.Column('change_author', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['change_author'], ['users.id'], ),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_strategy_versions_id'), 'strategy_versions', ['id'], unique=False)
    op.create_index(op.f('ix_strategy_versions_strategy_id'), 'strategy_versions', ['strategy_id'], unique=False)
    op.create_table('copied_trades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('follower_id', sa.Integer(), nullable=False),
    sa.Column('trader_id', sa.Integer(), nullable=False),
    sa.Column('original_trade_id', sa.Integer(), nullable=False),
    sa.Column('copied_trade_id', sa.Integer(), nullable=True),
    sa.Column('allocation_percentage', sa.Float(), nullable=False),
    sa.Column('original_amount', sa.Float(), nullable=False),
    sa.Column('copied_amount', sa.Float(), nullable=False),
    sa.Column('original_price', sa.Float(), nullable=False),
    sa.Column('copied_price', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['copied_trade_id'], ['trades.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['original_trade_id'], ['trades.id'], ),
    sa.ForeignKeyConstraint(['trader_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_copied_trades_copied_trade_id'), 'copied_trades', ['copied_trade_id'], unique=False)
    op.create_index(op.f('ix_copied_trades_follower_id'), 'copied_trades', ['follower_id'], unique=False)
    op.create_index(op.f('ix_copied_trades_id'), 'copied_trades', ['id'], unique=False)
    op.create_index(op.f('ix_copied_trades_original_trade_id'), 'copied_trades', ['original_trade_id'], unique=False)
    op.create_index(op.f('ix_copied_trades_trader_id'), 'copied_trades', ['trader_id'], unique=False)
    op.create_table('wallet_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wallet_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('transaction_type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('fee', sa.Float(), nullable=False),
    sa.Column('net_amount', sa.Float(), nullable=False),
    sa.Column('reference_id', sa.String(length=100), nullable=True),
    sa.Column('trade_id', sa.Integer(), nullable=True),
    sa.Column('payment_intent_id', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('transaction_metadata', sa.Text(), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['trade_id'], ['trades.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wallet_transactions_id'), 'wallet_transactions', ['id'], unique=False)
    op.create_index(op.f('ix_wallet_transactions_payment_intent_id'), 'wallet_transactions', ['payment_intent_id'], unique=False)
    op.create_index(op.f('ix_wallet_transactions_reference_id'), 'wallet_transactions', ['reference_id'], unique=False)
    op.create_index(op.f('ix_wallet_transactions_status'), 'wallet_transactions', ['status'], unique=False)
    op.create_index(op.f('ix_wallet_transactions_trade_id'), 'wallet_transactions', ['trade_id'], unique=False)
    op.create_index(op.f('ix_wallet_transactions_transaction_type'), 'wallet_transactions', ['transaction_type'], unique=False)
    op.create_index(op.f('ix_wallet_transactions_user_id'), 'wallet_transactions', ['user_id'], unique=False)
    op.create_index(op.f('ix_wallet_transactions_wallet_id'), 'wallet_transactions', ['wallet_id'], unique=False)
    # Check if we're using SQLite (requires batch mode for ALTER TABLE)
    bind = op.get_bind()
    is_sqlite = bind.dialect.name == 'sqlite'
    
    # Drop subscriptions table (if exists)
    try:
        op.drop_index('ix_subscriptions_stripe_customer_id', table_name='subscriptions')
    except Exception:
        pass
    try:
        op.drop_index('ix_subscriptions_stripe_subscription_id', table_name='subscriptions')
    except Exception:
        pass
    try:
        op.drop_index('ix_subscriptions_user_id', table_name='subscriptions')
    except Exception:
        pass
    try:
        op.drop_table('subscriptions')
    except Exception:
        pass
    
    # Drop indexes (if exist)
    try:
        op.drop_index('ix_bots_user_active', table_name='bots')
    except Exception:
        pass
    try:
        op.drop_index('ix_bots_user_status', table_name='bots')
    except Exception:
        pass
    
    # For SQLite, use batch mode for ALTER TABLE operations
    if is_sqlite:
        with op.batch_alter_table('bots', schema=None) as batch_op:
            # Foreign key will be created when table is recreated if needed
            pass
        with op.batch_alter_table('orders', schema=None) as batch_op:
            try:
                batch_op.drop_index('ix_orders_created_at')
            except Exception:
                pass
            try:
                batch_op.drop_index('ix_orders_order_type')
            except Exception:
                pass
            try:
                batch_op.drop_index('ix_orders_status')
            except Exception:
                pass
            try:
                batch_op.drop_index('ix_orders_symbol_status')
            except Exception:
                pass
            try:
                batch_op.drop_index('ix_orders_user_mode')
            except Exception:
                pass
            try:
                batch_op.drop_index('ix_orders_user_status')
            except Exception:
                pass
        with op.batch_alter_table('trades', schema=None) as batch_op:
            # Add new columns
            try:
                batch_op.add_column(sa.Column('grid_bot_id', sa.String(length=50), nullable=True))
            except Exception:
                pass  # Column may already exist
            try:
                batch_op.add_column(sa.Column('dca_bot_id', sa.String(length=50), nullable=True))
            except Exception:
                pass
            try:
                batch_op.add_column(sa.Column('infinity_grid_id', sa.String(length=50), nullable=True))
            except Exception:
                pass
            try:
                batch_op.add_column(sa.Column('trailing_bot_id', sa.String(length=50), nullable=True))
            except Exception:
                pass
            try:
                batch_op.add_column(sa.Column('futures_position_id', sa.String(length=50), nullable=True))
            except Exception:
                pass
            try:
                batch_op.add_column(sa.Column('pair', sa.String(), nullable=True))  # Make nullable first
            except Exception:
                pass
            try:
                batch_op.add_column(sa.Column('order_ref_id', sa.Integer(), nullable=True))
            except Exception:
                pass
            try:
                batch_op.add_column(sa.Column('pnl_percent', sa.Float(), nullable=True))
            except Exception:
                pass
            try:
                batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))  # Make nullable first
            except Exception:
                pass
            try:
                batch_op.add_column(sa.Column('timestamp', sa.DateTime(), nullable=True))  # Make nullable first
            except Exception:
                pass
            try:
                batch_op.add_column(sa.Column('total', sa.Float(), nullable=True))
            except Exception:
                pass
            # Note: ALTER COLUMN type changes in SQLite require table recreation, skip for now
    else:
        # For other databases (PostgreSQL, etc.)
        try:
            op.create_foreign_key(None, 'bots', 'users', ['user_id'], ['id'])
        except Exception:
            pass  # May already exist
        try:
            op.drop_index('ix_orders_created_at', table_name='orders')
        except Exception:
            pass
        try:
            op.drop_index('ix_orders_order_type', table_name='orders')
        except Exception:
            pass
        try:
            op.drop_index('ix_orders_status', table_name='orders')
        except Exception:
            pass
        try:
            op.drop_index('ix_orders_symbol_status', table_name='orders')
        except Exception:
            pass
        try:
            op.drop_index('ix_orders_user_mode', table_name='orders')
        except Exception:
            pass
        try:
            op.drop_index('ix_orders_user_status', table_name='orders')
        except Exception:
            pass
        try:
            op.drop_constraint(None, 'orders', type_='foreignkey')
        except Exception:
            pass
        try:
            op.drop_constraint(None, 'orders', type_='foreignkey')
        except Exception:
            pass
        try:
            op.create_foreign_key(None, 'orders', 'users', ['user_id'], ['id'])
        except Exception:
            pass
        try:
            op.create_foreign_key(None, 'orders', 'bots', ['bot_id'], ['id'])
        except Exception:
            pass
        try:
            op.add_column('trades', sa.Column('grid_bot_id', sa.String(length=50), nullable=True))
        except Exception:
            pass
        try:
            op.add_column('trades', sa.Column('dca_bot_id', sa.String(length=50), nullable=True))
        except Exception:
            pass
        try:
            op.add_column('trades', sa.Column('infinity_grid_id', sa.String(length=50), nullable=True))
        except Exception:
            pass
        try:
            op.add_column('trades', sa.Column('trailing_bot_id', sa.String(length=50), nullable=True))
        except Exception:
            pass
        try:
            op.add_column('trades', sa.Column('futures_position_id', sa.String(length=50), nullable=True))
        except Exception:
            pass
    
    # Drop other indexes (safe to try)
    try:
        op.drop_index('ix_portfolios_user_exchange', table_name='portfolios')
    except Exception:
        pass
    try:
        op.drop_index('ix_risk_alerts_user_created', table_name='risk_alerts')
    except Exception:
        pass
    try:
        op.drop_index('ix_risk_alerts_user_severity', table_name='risk_alerts')
    except Exception:
        pass
    
    # Add remaining trade columns (for non-SQLite or if not in batch mode)
    if not is_sqlite:
        try:
            op.add_column('trades', sa.Column('pair', sa.String(), nullable=False))
        except Exception:
            pass
        try:
            op.add_column('trades', sa.Column('order_ref_id', sa.Integer(), nullable=True))
        except Exception:
            pass
        try:
            op.add_column('trades', sa.Column('pnl_percent', sa.Float(), nullable=True))
        except Exception:
            pass
        try:
            op.add_column('trades', sa.Column('status', sa.String(length=20), nullable=False))
        except Exception:
            pass
        try:
            op.add_column('trades', sa.Column('timestamp', sa.DateTime(), nullable=False))
        except Exception:
            pass
        try:
            op.add_column('trades', sa.Column('total', sa.Float(), nullable=True))
        except Exception:
            pass
        try:
            op.alter_column('trades', 'user_id',
                       existing_type=sa.VARCHAR(),
                       type_=sa.Integer(),
                       existing_nullable=False)
        except Exception:
            pass
        try:
            op.alter_column('trades', 'bot_id',
                       existing_type=sa.INTEGER(),
                       type_=sa.String(length=50),
                       existing_nullable=True)
        except Exception:
            pass
    
    # Drop old indexes (safe to try)
    try:
        op.drop_index('ix_trades_executed_at_desc', table_name='trades')
    except Exception:
        pass
    try:
        op.drop_index('ix_trades_symbol_side', table_name='trades')
    except Exception:
        pass
    try:
        op.drop_index('ix_trades_user_mode_created', table_name='trades')
    except Exception:
        pass
    
    # Create new indexes
    try:
        op.create_index(op.f('ix_trades_dca_bot_id'), 'trades', ['dca_bot_id'], unique=False)
    except Exception:
        pass
    try:
        op.create_index(op.f('ix_trades_futures_position_id'), 'trades', ['futures_position_id'], unique=False)
    except Exception:
        pass
    try:
        op.create_index(op.f('ix_trades_grid_bot_id'), 'trades', ['grid_bot_id'], unique=False)
    except Exception:
        pass
    try:
        op.create_index(op.f('ix_trades_infinity_grid_id'), 'trades', ['infinity_grid_id'], unique=False)
    except Exception:
        pass
    try:
        op.create_index(op.f('ix_trades_order_ref_id'), 'trades', ['order_ref_id'], unique=False)
    except Exception:
        pass
    try:
        op.create_index(op.f('ix_trades_pair'), 'trades', ['pair'], unique=False)
    except Exception:
        pass
    try:
        op.create_index(op.f('ix_trades_timestamp'), 'trades', ['timestamp'], unique=False)
    except Exception:
        pass
    try:
        op.create_index(op.f('ix_trades_trailing_bot_id'), 'trades', ['trailing_bot_id'], unique=False)
    except Exception:
        pass
    
    # Create foreign keys (skip for SQLite as they're handled in batch mode or may already exist)
    if not is_sqlite:
        try:
            op.create_foreign_key(None, 'trades', 'users', ['user_id'], ['id'])
        except Exception:
            pass
        try:
            op.create_foreign_key(None, 'trades', 'grid_bots', ['grid_bot_id'], ['id'])
        except Exception:
            pass
        try:
            op.create_foreign_key(None, 'trades', 'bots', ['bot_id'], ['id'])
        except Exception:
            pass
        try:
            op.create_foreign_key(None, 'trades', 'infinity_grids', ['infinity_grid_id'], ['id'])
        except Exception:
            pass
        try:
            op.create_foreign_key(None, 'trades', 'orders', ['order_ref_id'], ['id'])
        except Exception:
            pass
        try:
            op.create_foreign_key(None, 'trades', 'trailing_bots', ['trailing_bot_id'], ['id'])
        except Exception:
            pass
        try:
            op.create_foreign_key(None, 'trades', 'dca_bots', ['dca_bot_id'], ['id'])
        except Exception:
            pass
        try:
            op.create_foreign_key(None, 'trades', 'futures_positions', ['futures_position_id'], ['id'])
        except Exception:
            pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'trades', type_='foreignkey')
    op.drop_constraint(None, 'trades', type_='foreignkey')
    op.drop_constraint(None, 'trades', type_='foreignkey')
    op.drop_constraint(None, 'trades', type_='foreignkey')
    op.drop_constraint(None, 'trades', type_='foreignkey')
    op.drop_constraint(None, 'trades', type_='foreignkey')
    op.drop_constraint(None, 'trades', type_='foreignkey')
    op.drop_constraint(None, 'trades', type_='foreignkey')
    op.drop_index(op.f('ix_trades_trailing_bot_id'), table_name='trades')
    op.drop_index(op.f('ix_trades_timestamp'), table_name='trades')
    op.drop_index(op.f('ix_trades_pair'), table_name='trades')
    op.drop_index(op.f('ix_trades_order_ref_id'), table_name='trades')
    op.drop_index(op.f('ix_trades_infinity_grid_id'), table_name='trades')
    op.drop_index(op.f('ix_trades_grid_bot_id'), table_name='trades')
    op.drop_index(op.f('ix_trades_futures_position_id'), table_name='trades')
    op.drop_index(op.f('ix_trades_dca_bot_id'), table_name='trades')
    op.create_index('ix_trades_user_mode_created', 'trades', ['user_id', 'mode', 'created_at'], unique=False)
    op.create_index('ix_trades_symbol_side', 'trades', ['symbol', 'side'], unique=False)
    op.create_index('ix_trades_executed_at_desc', 'trades', ['executed_at'], unique=False)
    op.alter_column('trades', 'bot_id',
               existing_type=sa.String(length=50),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('trades', 'user_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_column('trades', 'total')
    op.drop_column('trades', 'timestamp')
    op.drop_column('trades', 'status')
    op.drop_column('trades', 'pnl_percent')
    op.drop_column('trades', 'order_ref_id')
    op.drop_column('trades', 'pair')
    op.drop_column('trades', 'futures_position_id')
    op.drop_column('trades', 'trailing_bot_id')
    op.drop_column('trades', 'infinity_grid_id')
    op.drop_column('trades', 'dca_bot_id')
    op.drop_column('trades', 'grid_bot_id')
    op.create_index('ix_risk_alerts_user_severity', 'risk_alerts', ['user_id', 'severity'], unique=False)
    op.create_index('ix_risk_alerts_user_created', 'risk_alerts', ['user_id', 'created_at'], unique=False)
    op.create_index('ix_portfolios_user_exchange', 'portfolios', ['user_id', 'exchange'], unique=False)
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.create_foreign_key(None, 'orders', 'bots', ['bot_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'orders', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_index('ix_orders_user_status', 'orders', ['user_id', 'status'], unique=False)
    op.create_index('ix_orders_user_mode', 'orders', ['user_id', 'mode'], unique=False)
    op.create_index('ix_orders_symbol_status', 'orders', ['symbol', 'status'], unique=False)
    op.create_index('ix_orders_status', 'orders', ['status'], unique=False)
    op.create_index('ix_orders_order_type', 'orders', ['order_type'], unique=False)
    op.create_index('ix_orders_created_at', 'orders', ['created_at'], unique=False)
    op.drop_constraint(None, 'bots', type_='foreignkey')
    op.create_index('ix_bots_user_status', 'bots', ['user_id', 'status'], unique=False)
    op.create_index('ix_bots_user_active', 'bots', ['user_id', 'active'], unique=False)
    op.create_table('subscriptions',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('stripe_customer_id', sa.VARCHAR(length=255), nullable=True),
    sa.Column('stripe_subscription_id', sa.VARCHAR(length=255), nullable=True),
    sa.Column('stripe_price_id', sa.VARCHAR(length=255), nullable=True),
    sa.Column('plan', sa.VARCHAR(length=50), server_default=sa.text("'free'"), nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), server_default=sa.text("'inactive'"), nullable=False),
    sa.Column('current_period_start', sa.DATETIME(), nullable=True),
    sa.Column('current_period_end', sa.DATETIME(), nullable=True),
    sa.Column('cancel_at_period_end', sa.BOOLEAN(), server_default=sa.text("'false'"), nullable=False),
    sa.Column('trial_start', sa.DATETIME(), nullable=True),
    sa.Column('trial_end', sa.DATETIME(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.Column('deleted_at', sa.DATETIME(), nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), server_default=sa.text("'false'"), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index('ix_subscriptions_user_id', 'subscriptions', ['user_id'], unique=False)
    op.create_index('ix_subscriptions_stripe_subscription_id', 'subscriptions', ['stripe_subscription_id'], unique=False)
    op.create_index('ix_subscriptions_stripe_customer_id', 'subscriptions', ['stripe_customer_id'], unique=False)
    op.drop_index(op.f('ix_wallet_transactions_wallet_id'), table_name='wallet_transactions')
    op.drop_index(op.f('ix_wallet_transactions_user_id'), table_name='wallet_transactions')
    op.drop_index(op.f('ix_wallet_transactions_transaction_type'), table_name='wallet_transactions')
    op.drop_index(op.f('ix_wallet_transactions_trade_id'), table_name='wallet_transactions')
    op.drop_index(op.f('ix_wallet_transactions_status'), table_name='wallet_transactions')
    op.drop_index(op.f('ix_wallet_transactions_reference_id'), table_name='wallet_transactions')
    op.drop_index(op.f('ix_wallet_transactions_payment_intent_id'), table_name='wallet_transactions')
    op.drop_index(op.f('ix_wallet_transactions_id'), table_name='wallet_transactions')
    op.drop_table('wallet_transactions')
    op.drop_index(op.f('ix_copied_trades_trader_id'), table_name='copied_trades')
    op.drop_index(op.f('ix_copied_trades_original_trade_id'), table_name='copied_trades')
    op.drop_index(op.f('ix_copied_trades_id'), table_name='copied_trades')
    op.drop_index(op.f('ix_copied_trades_follower_id'), table_name='copied_trades')
    op.drop_index(op.f('ix_copied_trades_copied_trade_id'), table_name='copied_trades')
    op.drop_table('copied_trades')
    op.drop_index(op.f('ix_strategy_versions_strategy_id'), table_name='strategy_versions')
    op.drop_index(op.f('ix_strategy_versions_id'), table_name='strategy_versions')
    op.drop_table('strategy_versions')
    op.drop_index(op.f('ix_wallets_wallet_type'), table_name='wallets')
    op.drop_index(op.f('ix_wallets_user_id'), table_name='wallets')
    op.drop_index(op.f('ix_wallets_id'), table_name='wallets')
    op.drop_index(op.f('ix_wallets_currency'), table_name='wallets')
    op.drop_table('wallets')
    op.drop_index(op.f('ix_trailing_bots_user_id'), table_name='trailing_bots')
    op.drop_index(op.f('ix_trailing_bots_symbol'), table_name='trailing_bots')
    op.drop_index(op.f('ix_trailing_bots_id'), table_name='trailing_bots')
    op.drop_table('trailing_bots')
    op.drop_index(op.f('ix_strategies_user_id'), table_name='strategies')
    op.drop_index(op.f('ix_strategies_id'), table_name='strategies')
    op.drop_table('strategies')
    op.drop_index(op.f('ix_infinity_grids_user_id'), table_name='infinity_grids')
    op.drop_index(op.f('ix_infinity_grids_symbol'), table_name='infinity_grids')
    op.drop_index(op.f('ix_infinity_grids_id'), table_name='infinity_grids')
    op.drop_table('infinity_grids')
    op.drop_index(op.f('ix_idempotency_keys_user_id'), table_name='idempotency_keys')
    op.drop_index(op.f('ix_idempotency_keys_key'), table_name='idempotency_keys')
    op.drop_index(op.f('ix_idempotency_keys_expires_at'), table_name='idempotency_keys')
    op.drop_table('idempotency_keys')
    op.drop_index(op.f('ix_grid_bots_user_id'), table_name='grid_bots')
    op.drop_index(op.f('ix_grid_bots_symbol'), table_name='grid_bots')
    op.drop_index(op.f('ix_grid_bots_id'), table_name='grid_bots')
    op.drop_table('grid_bots')
    op.drop_index(op.f('ix_futures_positions_user_id'), table_name='futures_positions')
    op.drop_index(op.f('ix_futures_positions_symbol'), table_name='futures_positions')
    op.drop_index(op.f('ix_futures_positions_id'), table_name='futures_positions')
    op.drop_table('futures_positions')
    op.drop_index(op.f('ix_follows_trader_id'), table_name='follows')
    op.drop_index(op.f('ix_follows_id'), table_name='follows')
    op.drop_index(op.f('ix_follows_follower_id'), table_name='follows')
    op.drop_table('follows')
    op.drop_index(op.f('ix_dca_bots_user_id'), table_name='dca_bots')
    op.drop_index(op.f('ix_dca_bots_symbol'), table_name='dca_bots')
    op.drop_index(op.f('ix_dca_bots_id'), table_name='dca_bots')
    op.drop_table('dca_bots')
    # ### end Alembic commands ###

