"""add_trade_mode_and_audit_fields

Revision ID: f49a0f90e8a9
Revises: 7403273b52d2
Create Date: 2025-11-14 23:37:33.505949

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f49a0f90e8a9'
down_revision = '7403273b52d2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    dialect_name = bind.dialect.name if bind is not None else None

    # Introspect existing schema so we can safely run on dev SQLite
    # databases that may already have some of these columns from
    # previous experiments or partial migrations.
    inspector = sa.inspect(bind)
    existing_columns = {col["name"] for col in inspector.get_columns("trades")}
    existing_indexes = {idx["name"] for idx in inspector.get_indexes("trades")}

    if "order_type" not in existing_columns:
        op.add_column("trades", sa.Column("order_type", sa.String(), nullable=False))
    if "mode" not in existing_columns:
        op.add_column("trades", sa.Column("mode", sa.String(), nullable=False))
    if "pnl" not in existing_columns:
        op.add_column("trades", sa.Column("pnl", sa.Float(), nullable=True))
    if "audit_logged" not in existing_columns:
        op.add_column("trades", sa.Column("audit_logged", sa.Boolean(), nullable=False))
    # NOTE:
    # SQLite has very limited ALTER TABLE support and does not support
    # "ALTER COLUMN ... TYPE" in the same way as PostgreSQL. The generic
    # SQL emitted by Alembic here fails on SQLite with:
    #   sqlite3.OperationalError: near "ALTER": syntax error
    #
    # For development where SQLite is used, we skip this type change and
    # keep the existing column definition. On PostgreSQL (or other backends
    # that support ALTER COLUMN TYPE) we still apply the migration.
    if dialect_name != "sqlite":
        op.alter_column(
            'trades',
            'user_id',
            existing_type=sa.VARCHAR(),
            type_=sa.Integer(),
            existing_nullable=False,
        )

    ix_executed_at = op.f("ix_trades_executed_at")
    ix_mode = op.f("ix_trades_mode")
    if ix_executed_at not in existing_indexes:
        op.create_index(ix_executed_at, "trades", ["executed_at"], unique=False)
    if ix_mode not in existing_indexes:
        op.create_index(ix_mode, "trades", ["mode"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trades_mode'), table_name='trades')
    op.drop_index(op.f('ix_trades_executed_at'), table_name='trades')
    op.alter_column('trades', 'user_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_column('trades', 'audit_logged')
    op.drop_column('trades', 'pnl')
    op.drop_column('trades', 'mode')
    op.drop_column('trades', 'order_type')
    # ### end Alembic commands ###

